### PR TITLE
Fixes #635 - bug in async server's connection read

### LINKED ISSUE #635: async_connection: read function calls callback with too few parameters
Having a look at:
[async_connection.hpp line 395](https://github.com/cpp-netlib/cpp-netlib/blob/de9194d7e2525baca2711f40aa1d7b8ed96667d1/boost/network/protocol/http/server/async_connection.hpp#L395)

The read function from async_connection calls the read_callback_function with 2 instead of 4 needed parameters, this leads into this compiling issue (when using the read function):

    async_connection.hpp | 395 |
    error: no match for call to ‘(const read_callback_function {aka const std::function<void(boost::iterator_range<const char*>, std::error_code, long unsigned int, std::shared_ptr<boost::network::http::async_connection<boost::network::http::tags::http_server, {anonymous}::serverhandle> >)>}) (std::error_code&, size_t&)’|

First reported here: [cpp-netlib google groups](https://groups.google.com/d/msg/cpp-netlib/fgiy6c3kSc0/MiB9502VAAAJ)

### PR DESCRIPTION
**Pull request by deanberris**
This changes the example file server to use the read handler for
POST/PUT requests. This currently assumes that there's a content-length
header (not much error handling is happening here, but it's meant as a
proof of concept anyway).

Using this code path in an example should be good enough for the moment
until we have better tests and a better API for this functionality.

### CODE REVIEW

**Comment by deanberris** [comment]
References #635 -- looking for reviewers and people to try it out.

File: boost/network/protocol/http/server/async_connection.hpp [hunk 1]
```diff
@@ -389,11 +389,12 @@ struct async_connection
     }
 
     auto self = this->shared_from_this();
```
Comment (susnux) [inline boost/network/protocol/http/server/async_connection.hpp]: You do not  need `self` here anymore, since it is not used in the lambda (can also be removed from the capture section of the lambda).

Comment (deanberris) [inline boost/network/protocol/http/server/async_connection.hpp]: Actually, this "self" variable makes sure that the object is alive -- it ensures that there's a shared reference in the callback that depends on the state of the connection. It's a trick that's tied to how asynchronous programming is really hard to debug. 😀

Comment (susnux) [inline boost/network/protocol/http/server/async_connection.hpp]: @deanberris Your right thought it would be something like this.
But is then then "this" needed (self->... should be enough or am I wrong?).
